### ISSUE TITLE
HuggingFace recordings broken

### ISSUE THREAD

**Issue by abhilashi** [McGill-NLP/weblinx#6] opened 2024-02-15 01:12 UTC
<img width="1760" alt="Screenshot 2024-02-15 at 06 40 22" src="https://github.com/McGill-NLP/weblinx/assets/4708378/667ee929-49a0-47ec-9511-1eaa20d72e88">

Here is the trace:

`File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/app.py", line 260, in <module>
    run()
File "/home/user/app/app.py", line 250, in run
    data = load_recording(basedir=basedir)
File "/home/user/app/app.py", line 145, in load_recording
    metadata = load_json(basedir, "metadata")
File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 268, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 324, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
File "/home/user/app/utils.py", line 32, in load_json
    j = json.load(f)
File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None`

URL: https://huggingface.co/spaces/McGill-NLP/weblinx-explorer?recording=aaabtsd

**Comment by xhluca** [comment] 2024-02-15 22:08
Thanks for reporting this. It seems the issue is on the Huggingface Spaces side - perhaps due to the size or number of files in the repository.

I have removed the offending recordings; we can role back the commits if it is fixed in the futre.

**Closed by xhluca** 2024-02-15 22:08 UTC
